from enum import Enum


class CountryEnum(Enum):
    AF = "af"  # Afghanistan
    AL = "al"  # Albania
    DZ = "dz"  # Algeria
    AS = "as"  # American Samoa
    AD = "ad"  # Andorra
    AO = "ao"  # Angola
    AI = "ai"  # Anguilla
    AQ = "aq"  # Antarctica
    AG = "ag"  # Antigua and Barbuda
    AR = "ar"  # Argentina
    AM = "am"  # Armenia
    AW = "aw"  # Aruba
    AU = "au"  # Australia
    AT = "at"  # Austria
    AZ = "az"  # Azerbaijan
    BS = "bs"  # Bahamas
    BH = "bh"  # Bahrain
    BD = "bd"  # Bangladesh
    BB = "bb"  # Barbados
    BY = "by"  # Belarus
    BE = "be"  # Belgium
    BZ = "bz"  # Belize
    BJ = "bj"  # Benin
    BM = "bm"  # Bermuda
    BT = "bt"  # Bhutan
    BO = "bo"  # Bolivia
    BA = "ba"  # Bosnia and Herzegovina
    BW = "bw"  # Botswana
    BV = "bv"  # Bouvet Island
    BR = "br"  # Brazil
    IO = "io"  # British Indian Ocean Territory
    BN = "bn"  # Brunei Darussalam
    BG = "bg"  # Bulgaria
    BF = "bf"  # Burkina Faso
    BI = "bi"  # Burundi
    KH = "kh"  # Cambodia
    CM = "cm"  # Cameroon
    CA = "ca"  # Canada
    CV = "cv"  # Cape Verde
    KY = "ky"  # Cayman Islands
    CF = "cf"  # Central African Republic
    TD = "td"  # Chad
    CL = "cl"  # Chile
    CN = "cn"  # China
    CX = "cx"  # Christmas Island
    CC = "cc"  # Cocos (Keeling) Islands
    CO = "co"  # Colombia
    KM = "km"  # Comoros
    CG = "cg"  # Congo
    CD = "cd"  # Congo, the Democratic Republic of the
    CK = "ck"  # Cook Islands
    CR = "cr"  # Costa Rica
    CI = "ci"  # Cote D'ivoire
    HR = "hr"  # Croatia
    CU = "cu"  # Cuba
    CY = "cy"  # Cyprus
    CZ = "cz"  # Czech Republic
    DK = "dk"  # Denmark
    DJ = "dj"  # Djibouti
    DM = "dm"  # Dominica
    DO = "do"  # Dominican Republic
    EC = "ec"  # Ecuador
    EG = "eg"  # Egypt
    SV = "sv"  # El Salvador
    GQ = "gq"  # Equatorial Guinea
    ER = "er"  # Eritrea
    EE = "ee"  # Estonia
    ET = "et"  # Ethiopia
    FK = "fk"  # Falkland Islands (Malvinas)
    FO = "fo"  # Faroe Islands
    FJ = "fj"  # Fiji
    FI = "fi"  # Finland
    FR = "fr"  # France
    GF = "gf"  # French Guiana
    PF = "pf"  # French Polynesia
    TF = "tf"  # French Southern Territories
    GA = "ga"  # Gabon
    GM = "gm"  # Gambia
    GE = "ge"  # Georgia
    DE = "de"  # Germany
    GH = "gh"  # Ghana
    GI = "gi"  # Gibraltar
    GR = "gr"  # Greece
    GL = "gl"  # Greenland
    GD = "gd"  # Grenada
    GP = "gp"  # Guadeloupe
    GU = "gu"  # Guam
    GT = "gt"  # Guatemala
    GN = "gn"  # Guinea
    GW = "gw"  # Guinea-Bissau
    GY = "gy"  # Guyana
    HT = "ht"  # Haiti
    HM = "hm"  # Heard Island and Mcdonald Islands
    VA = "va"  # Holy See (Vatican City State)
    HN = "hn"  # Honduras
    HK = "hk"  # Hong Kong
    HU = "hu"  # Hungary
    IS = "is"  # Iceland
    IN = "in"  # India
    ID = "id"  # Indonesia
    IR = "ir"  # Iran, Islamic Republic of
    IQ = "iq"  # Iraq
    IE = "ie"  # Ireland
    IL = "il"  # Israel
    IT = "it"  # Italy
    JM = "jm"  # Jamaica
    JP = "jp"  # Japan
    JO = "jo"  # Jordan
    KZ = "kz"  # Kazakhstan
    KE = "ke"  # Kenya
    KI = "ki"  # Kiribati
    KP = "kp"  # Korea, Democratic People's Republic of
    KR = "kr"  # Korea, Republic of
    KW = "kw"  # Kuwait
    KG = "kg"  # Kyrgyzstan
    LA = "la"  # Lao People's Democratic Republic
    LV = "lv"  # Latvia
    LB = "lb"  # Lebanon
    LS = "ls"  # Lesotho
    LR = "lr"  # Liberia
    LY = "ly"  # Libyan Arab Jamahiriya
    LI = "li"  # Liechtenstein
    LT = "lt"  # Lithuania
    LU = "lu"  # Luxembourg
    MO = "mo"  # Macao
    MK = "mk"  # Macedonia, the Former Yugoslav Republic of
    MG = "mg"  # Madagascar
    MW = "mw"  # Malawi
    MY = "my"  # Malaysia
    MV = "mv"  # Maldives
    ML = "ml"  # Mali
    MT = "mt"  # Malta
    MH = "mh"  # Marshall Islands
    MQ = "mq"  # Martinique
    MR = "mr"  # Mauritania
    MU = "mu"  # Mauritius
    YT = "yt"  # Mayotte
    MX = "mx"  # Mexico
    FM = "fm"  # Micronesia, Federated States of
    MD = "md"  # Moldova, Republic of
    MC = "mc"  # Monaco
    MN = "mn"  # Mongolia
    MS = "ms"  # Montserrat
    MA = "ma"  # Morocco
    MZ = "mz"  # Mozambique
    MM = "mm"  # Myanmar
    NA = "na"  # Namibia
    NR = "nr"  # Nauru
    NP = "np"  # Nepal
    NL = "nl"  # Netherlands
    AN = "an"  # Netherlands Antilles
    NC = "nc"  # New Caledonia
    NZ = "nz"  # New Zealand
    NI = "ni"  # Nicaragua
    NE = "ne"  # Niger
    NG = "ng"  # Nigeria
    NU = "nu"  # Niue
    NF = "nf"  # Norfolk Island
    MP = "mp"  # Northern Mariana Islands
    NO = "no"  # Norway
    OM = "om"  # Oman
    PK = "pk"  # Pakistan
    PW = "pw"  # Palau
    PS = "ps"  # Palestinian Territory, Occupied
    PA = "pa"  # Panama
    PG = "pg"  # Papua New Guinea
    PY = "py"  # Paraguay
    PE = "pe"  # Peru
    PH = "ph"  # Philippines
    PN = "pn"  # Pitcairn
    PL = "pl"  # Poland
    PT = "pt"  # Portugal
    PR = "pr"  # Puerto Rico
    QA = "qa"  # Qatar
    RE = "re"  # Reunion
    RO = "ro"  # Romania
    RU = "ru"  # Russian Federation
    RW = "rw"  # Rwanda
    SH = "sh"  # Saint Helena
    KN = "kn"  # Saint Kitts and Nevis
    LC = "lc"  # Saint Lucia
    PM = "pm"  # Saint Pierre and Miquelon
    VC = "vc"  # Saint Vincent and the Grenadines
    WS = "ws"  # Samoa
    SM = "sm"  # San Marino
    ST = "st"  # Sao Tome and Principe
    SA = "sa"  # Saudi Arabia
    SN = "sn"  # Senegal
    CS = "cs"  # Serbia and Montenegro
    SC = "sc"  # Seychelles
    SL = "sl"  # Sierra Leone
    SG = "sg"  # Singapore
    SK = "sk"  # Slovakia
    SI = "si"  # Slovenia
    SB = "sb"  # Solomon Islands
    SO = "so"  # Somalia
    ZA = "za"  # South Africa
    GS = "gs"  # South Georgia and the South Sandwich Islands
    ES = "es"  # Spain
    LK = "lk"  # Sri Lanka
    SD = "sd"  # Sudan
    SR = "sr"  # Suriname
    SJ = "sj"  # Svalbard and Jan Mayen
    SZ = "sz"  # Swaziland
    SE = "se"  # Sweden
    CH = "ch"  # Switzerland
    SY = "sy"  # Syrian Arab Republic
    TW = "tw"  # Taiwan, Province of China
    TJ = "tj"  # Tajikistan
    TZ = "tz"  # Tanzania, United Republic of
    TH = "th"  # Thailand
    TL = "tl"  # Timor-Leste
    TG = "tg"  # Togo
    TK = "tk"  # Tokelau
    TO = "to"  # Tonga
    TT = "tt"  # Trinidad and Tobago
    TN = "tn"  # Tunisia
    TR = "tr"  # Turkey
    TM = "tm"  # Turkmenistan
    TC = "tc"  # Turks and Caicos Islands
    TV = "tv"  # Tuvalu
    UG = "ug"  # Uganda
    UA = "ua"  # Ukraine
    AE = "ae"  # United Arab Emirates
    UK = "uk"  # United Kingdom
    US = "us"  # United States
    UM = "um"  # United States Minor Outlying Islands
    UY = "uy"  # Uruguay
    UZ = "uz"  # Uzbekistan
    VU = "vu"  # Vanuatu
    VE = "ve"  # Venezuela
    VN = "vn"  # Viet Nam
    VG = "vg"  # Virgin Islands, British
    VI = "vi"  # Virgin Islands, U.S.
    WF = "wf"  # Wallis and Futuna
    EH = "eh"  # Western Sahara
    YE = "ye"  # Yemen
    ZM = "zm"  # Zambia
    ZW = "zw"  # Zimbabwe
