FROM python:3.12-slim

WORKDIR /usr/src/app
ENV FLASK_APP=app FLASK_RUN_HOST=0.0.0.0 FLASK_DEBUG=1

COPY /app/requirements.txt ./

RUN pip install -r requirements.txt
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY /app ./app

WORKDIR /usr/src/app/app
COPY entrypoint-api.sh ./
RUN chmod +x entrypoint-api.sh

CMD ["./entrypoint-api.sh"]

