"""add talent_profile_id foreign key to talent_user_invitations

Revision ID: 17e6470a1ea1
Revises: 8c0fde1836f2
Create Date: 2024-05-23 08:13:56.587720

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '17e6470a1ea1'
down_revision = '8c0fde1836f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_user_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('talent_profile_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=True))
        batch_op.create_foreign_key(None, 'talent_profiles', ['talent_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_user_invitations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('talent_profile_id')

    # ### end Alembic commands ###
