"""Add country to article_search_keywords table

Revision ID: 22f875431de5
Revises: be5051ab6710
Create Date: 2024-02-15 20:47:31.364988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22f875431de5'
down_revision = 'be5051ab6710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_search_keywords', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article_search_keywords', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
