"""separate celery task id and document_processing_task id

Revision ID: 29bcb05393e0
Revises: 6886706a2611
Create Date: 2024-05-10 12:15:29.867751

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '29bcb05393e0'
down_revision = '6886706a2611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_processing_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_task_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_processing_tasks', schema=None) as batch_op:
        batch_op.drop_column('current_task_id')

    # ### end Alembic commands ###
