"""Remove body from  articles table

Revision ID: 445267cc185d
Revises: c542e40e746a
Create Date: 2024-02-17 19:45:47.213664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445267cc185d'
down_revision = 'c542e40e746a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('body')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
