"""add language to agency_users

Revision ID: 6103866149cb
Revises: d5263defd10c
Create Date: 2024-04-30 09:58:18.367315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '6103866149cb'
down_revision = 'd5263defd10c'
branch_labels = None
depends_on = None


def upgrade():
    language = postgresql.ENUM('en', 'jp', 'id', name='language')
    language.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.Enum('en', 'jp', 'id', name='language'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_users', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
    language = postgresql.ENUM('en', 'jp', 'id', name='language')
    language.drop(op.get_bind())
