"""add language to agency_users

Revision ID: 701f95737834
Revises: d5263defd10c
Create Date: 2024-04-30 09:14:21.953059

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '701f95737834'
down_revision = 'd5263defd10c'
branch_labels = None
depends_on = None


def upgrade():
    language = postgresql.ENUM('English', 'Japanese', 'Indonesian', name='language')
    language.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.Enum('English', 'Japanese', 'Indonesian', name='language'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_users', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
    language = postgresql.ENUM('English', 'Japanese', 'Indonesian', name='language')
    language.drop(op.get_bind())
