"""Add summary and snippet to articles table

Revision ID: 7964aa29fb1e
Revises: 22f875431de5
Create Date: 2024-02-16 20:07:27.003260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7964aa29fb1e'
down_revision = '22f875431de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snippet', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('summary')
        batch_op.drop_column('snippet')

    # ### end Alembic commands ###
