"""add language field to agency_user

Revision ID: 79e48e74c6f6
Revises: eb92f3b81892
Create Date: 2024-05-08 04:32:23.608014

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '79e48e74c6f6'
down_revision = 'eb92f3b81892'
branch_labels = None
depends_on = None


def upgrade():
    language = postgresql.ENUM('en', 'ja', 'id', name='language')
    language.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.Enum('en', 'ja', 'id', name='language'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_users', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###

    language = postgresql.ENUM('en', 'ja', 'id', name='language')
    language.drop(op.get_bind())
