"""set some fields to required

Revision ID: 83c72dc7f872
Revises: d5263defd10c
Create Date: 2024-05-03 06:13:53.420766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83c72dc7f872'
down_revision = 'd5263defd10c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_document_imports', schema=None) as batch_op:
        batch_op.alter_column('json',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('talent_documents', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('kind',
               existing_type=postgresql.ENUM('cover_letter', name='talentdocumentkind'),
               nullable=False)
        batch_op.alter_column('json',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('talent_profiles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_profiles', schema=None) as batch_op:
        batch_op.alter_column('avatar',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('talent_documents', schema=None) as batch_op:
        batch_op.alter_column('json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('kind',
               existing_type=postgresql.ENUM('cover_letter', name='talentdocumentkind'),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('talent_document_imports', schema=None) as batch_op:
        batch_op.alter_column('json',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
