"""rename table; change url length column

Revision ID: 86ce7acc90d9
Revises: 29bcb05393e0
Create Date: 2024-05-20 07:22:39.820628

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86ce7acc90d9'
down_revision = '29bcb05393e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_processing_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celery_task_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False))
        batch_op.alter_column('document_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=2083),
               existing_nullable=False)
        batch_op.drop_column('current_task_id')

    with op.batch_alter_table('talent_document_imports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.String(length=2083), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_document_imports', schema=None) as batch_op:
        batch_op.drop_column('file_url')

    with op.batch_alter_table('document_processing_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_task_id', postgresql.UUID(), autoincrement=False, nullable=False))
        batch_op.alter_column('document_url',
               existing_type=sa.String(length=2083),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('celery_task_id')

    # ### end Alembic commands ###
