"""add invited_at column to talent_user_invitations

Revision ID: 8c0fde1836f2
Revises: faf106f1c4b5
Create Date: 2024-05-23 08:01:09.737446

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '8c0fde1836f2'
down_revision = 'faf106f1c4b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_user_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invited_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_user_invitations', schema=None) as batch_op:
        batch_op.drop_column('invited_at')

    # ### end Alembic commands ###
