"""temporary set some fields to optional

Revision ID: a9476fb5da2d
Revises: 3442cf26933f
Create Date: 2024-04-25 08:09:47.875713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9476fb5da2d'
down_revision = '3442cf26933f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_document_imports', schema=None) as batch_op:
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('talent_documents', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('talent_profiles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_profiles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('talent_documents', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('talent_document_imports', schema=None) as batch_op:
        batch_op.alter_column('file_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
