"""Delete organization columns from leads table

Revision ID: a991365e708a
Revises: d6b319b65764
Create Date: 2024-02-27 22:04:29.352130

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a991365e708a"
down_revision = "d6b319b65764"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.drop_column("organization_description")
        batch_op.drop_column("organization_url")
        batch_op.drop_column("organization_phone")
        batch_op.drop_column("organization_country")
        batch_op.drop_column("organization_name")
        batch_op.drop_column("organization_logo")
        batch_op.drop_column("organization_linkedin_url")
        batch_op.drop_column("organization_industry")
        batch_op.drop_column("organization_region")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("leads", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "organization_region",
                sa.VARCHAR(length=50),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "organization_industry",
                sa.VARCHAR(length=100),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "organization_linkedin_url",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "organization_logo",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "organization_name",
                sa.VARCHAR(length=100),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "organization_country",
                sa.VARCHAR(length=50),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "organization_phone",
                sa.VARCHAR(length=20),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "organization_url",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "organization_description",
                sa.TEXT(),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
