"""add language field to user table

Revision ID: ae22d2d95340
Revises: d5263defd10c
Create Date: 2024-05-06 03:39:06.927130

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae22d2d95340'
down_revision = 'd5263defd10c'
branch_labels = None
depends_on = None


def upgrade():
    language = postgresql.ENUM('en', 'jp', 'id', name='language')
    language.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agency_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.Enum('en', 'jp', 'id', name='language'), nullable=False))

    with op.batch_alter_table('talent_document_imports', schema=None) as batch_op:
        batch_op.alter_column('json',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('talent_documents', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('kind',
               existing_type=postgresql.ENUM('cover_letter', name='talentdocumentkind'),
               nullable=False)
        batch_op.alter_column('json',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('talent_profiles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('bio',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_profiles', schema=None) as batch_op:
        batch_op.alter_column('bio',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('talent_documents', schema=None) as batch_op:
        batch_op.alter_column('json',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('kind',
               existing_type=postgresql.ENUM('cover_letter', name='talentdocumentkind'),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('talent_document_imports', schema=None) as batch_op:
        batch_op.alter_column('json',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('agency_users', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###

    language = postgresql.ENUM('en', 'jp', 'id', name='language')
    language.drop(op.get_bind())
