"""Add body types to articles table

Revision ID: c542e40e746a
Revises: 59510bb4309d
Create Date: 2024-02-17 19:44:10.754395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c542e40e746a'
down_revision = '59510bb4309d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_original', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('body_translated', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('body_translated')
        batch_op.drop_column('body_original')

    # ### end Alembic commands ###
