"""add agency_id on talent_documents table

Revision ID: d5263defd10c
Revises: a9476fb5da2d
Create Date: 2024-04-26 10:40:24.499553

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'd5263defd10c'
down_revision = 'a9476fb5da2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False))
        batch_op.create_foreign_key(None, 'agencies', ['agency_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('agency_id')

    # ### end Alembic commands ###
