"""Create tenant_credit_transactions table

Revision ID: d6b319b65764
Revises: d4f63b5c4a09
Create Date: 2024-02-27 05:17:02.824178

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = "d6b319b65764"
down_revision = "d4f63b5c4a09"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenant_credit_transactions",
        sa.Column(
            "id", sqlalchemy_utils.types.uuid.UUIDType(binary=False), nullable=False
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum("added", "used", name="transaction_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "tenant_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=False,
        ),
        sa.Column(
            "related_subscription_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["related_subscription_id"],
            ["subscription_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tenant_credit_transactions")
    # ### end Alembic commands ###
