"""add email column to talent_profiles table

Revision ID: faf106f1c4b5
Revises: e63a56b8e579
Create Date: 2024-05-16 13:06:15.912781

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'faf106f1c4b5'
down_revision = 'e63a56b8e579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent_profiles', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
