version: "3"

services:
  celery:
    container_name: globaltalentdb-celery
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    volumes:
      - ./app:/usr/src/app/app
    depends_on:
      - redis
    env_file:
      - .env
    command: celery -A app.app.celery worker --loglevel=info

  api:
    container_name: globaltalentdb-api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/usr/src/app/app
    depends_on:
      - db
      - celery
    env_file:
      - .env
    command: flask run --host=0.0.0.0 --port 8080

  db:
    container_name: globaltalentdb-db
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - globaltalentdb-db-store:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    container_name: globaltalentdb-redis
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - globaltalentdb-redis-store:/root/redis
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379

volumes:
  globaltalentdb-db-store:
  globaltalentdb-redis-store:
