name: "Auto Assign"
on:
  pull_request:
    types: [opened, ready_for_review]
jobs:
  add-reviewers-and-assignees:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/auto_assign.yml"
