name: Vercel Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - frontend/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Extract branch name
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Deploy to Vercel
        continue-on-error: true
        run: vercel deploy --meta branchName=${{ steps.extract_branch.outputs.branch }} --token=${{ secrets.VERCEL_API_KEY }}
        env:
          VERCEL_API_KEY: ${{ secrets.VERCEL_API_KEY }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
